### ISSUE TITLE
small problems

### ISSUE THREAD

**Issue by ahstax** [sipgate-io/sipgateio-sendfax-java#1]
Thanks for stopping by to let us know something could be better!

Please be sure to include as much information as possible:

#### Environment details

- OS: Win 10 Pro
- Java version: jdk1.8.0_291

#### Steps to reproduce

1. sending a fax using a batchfile with this code "call %path% run --args="%receipient% %PDF%""

#### Stacktrace

1.
*********************
> Task :run FAILED
Exception in thread "main" org.json.JSONException: JSONObject["faxStatusType"] not found.
        at org.json.JSONObject.get(JSONObject.java:471)
        at org.json.JSONObject.getString(JSONObject.java:717)
        at sipgateio.sendfax.SendFax.pollSendStatus(SendFax.java:134)
        at sipgateio.sendfax.SendFax.main(SendFax.java:78)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_291\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
3 actionable tasks: 1 executed, 2 up-to-date
*********************

2.
the fax is sent twice and corresponding the report is sent twice.

3.
I'd like to automate further an read out the reports automatically. Therefore it would be great if the report or the copy of the fax could be named after the file to be faxed.

#### External references such as API reference guides used

- ?

#### Any additional information below

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nilsreck** [comment]
Hello,

thank you for reaching out. 
Regarding your first point, it seems like the Gradle project is not building. However, in your second point you argue that the fax is sent twice. Could you please further elaborate what your main issue is?
Can you successfully build the project? 
If you only run the project once, only one fax will be sent. Is it possible that you executed two instances of the Gradle project, which would explain the duplicate faxes.

Best regards,
Nils from sipgate.io
